CREATE TABLE `fmcontent_content` (
  `content_id`        INT(10)          NOT NULL AUTO_INCREMENT,
  `content_title`     VARCHAR(255)     NOT NULL,
  `content_titleview` TINYINT(1)       NOT NULL DEFAULT '1',
  `content_topic`     INT(11)          NOT NULL,
  `content_menu`      VARCHAR(255)     NOT NULL,
  `content_type`      VARCHAR(25)      NOT NULL,
  `content_short`     TEXT             NOT NULL,
  `content_text`      TEXT             NOT NULL,
  `content_link`      VARCHAR(255)     NOT NULL DEFAULT '',
  `content_words`     TEXT             NOT NULL,
  `content_desc`      TEXT             NOT NULL,
  `content_alias`     VARCHAR(255)     NOT NULL DEFAULT '',
  `content_display`   TINYINT(1)       NOT NULL,
  `content_default`   TINYINT(1)       NOT NULL,
  `content_status`    TINYINT(1)       NOT NULL,
  `content_create`    INT(10)          NOT NULL DEFAULT '0',
  `content_update`    INT(10)          NOT NULL DEFAULT '0',
  `content_uid`       INT(11)          NOT NULL,
  `content_author`    VARCHAR(255)     NOT NULL DEFAULT '',
  `content_source`    VARCHAR(255)     NOT NULL DEFAULT '',
  `content_groups`    VARCHAR(255)     NOT NULL DEFAULT '',
  `content_order`     INT(11)          NOT NULL,
  `content_next`      INT(11)          NOT NULL DEFAULT '0',
  `content_prev`      INT(11)          NOT NULL DEFAULT '0',
  `content_modid`     INT(11)          NOT NULL,
  `content_hits`      INT(11)          NOT NULL DEFAULT '0',
  `content_img`       VARCHAR(255)     NOT NULL DEFAULT '',
  `content_comments`  INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `content_file`      TINYINT(3)       NOT NULL DEFAULT '0',
  `dohtml`            TINYINT(1)       NOT NULL,
  `dobr`              TINYINT(1)       NOT NULL,
  `doimage`           TINYINT(1)       NOT NULL,
  `dosmiley`          TINYINT(1)       NOT NULL,
  `doxcode`           TINYINT(1)       NOT NULL,
  PRIMARY KEY (`content_id`, `content_modid`),
  UNIQUE KEY `content_id` (`content_id`, `content_modid`)
)
  ENGINE = MyISAM;


CREATE TABLE `fmcontent_topic` (
  `topic_id`           INT(11) UNSIGNED NOT NULL  AUTO_INCREMENT,
  `topic_pid`          INT(5) UNSIGNED  NOT NULL,
  `topic_title`        VARCHAR(255)     NOT NULL,
  `topic_desc`         TEXT             NOT NULL,
  `topic_img`          VARCHAR(255)     NOT NULL  DEFAULT '',
  `topic_weight`       INT(5)           NOT NULL,
  `topic_showtype`     TINYINT(4)       NOT NULL,
  `topic_perpage`      TINYINT(4)       NOT NULL,
  `topic_columns`      TINYINT(4)       NOT NULL,
  `topic_submitter`    INT(10)          NOT NULL  DEFAULT '0',
  `topic_date_created` INT(10)          NOT NULL  DEFAULT '0',
  `topic_date_update`  INT(10)          NOT NULL  DEFAULT '0',
  `topic_asmenu`       TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_online`       TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_modid`        INT(11)          NOT NULL,
  `topic_showtopic`    TINYINT(1)       NOT NULL  DEFAULT '0',
  `topic_showauthor`   TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_showdate`     TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_showpdf`      TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_showprint`    TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_showmail`     TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_shownav`      TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_showhits`     TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_showcoms`     TINYINT(1)       NOT NULL  DEFAULT '1',
  `topic_alias`        VARCHAR(255)     NOT NULL,
  `topic_homepage`     TINYINT(4)       NOT NULL,
  `topic_show`         TINYINT(1)       NOT NULL  DEFAULT '1',
  PRIMARY KEY (`topic_id`, `topic_modid`),
  UNIQUE KEY `topic_id` (`topic_id`, `topic_modid`)
)
  ENGINE = MyISAM;

CREATE TABLE `fmcontent_file` (
  `file_id`      INT(11) UNSIGNED NOT NULL  AUTO_INCREMENT,
  `file_modid`   INT(11)          NOT NULL,
  `file_title`   VARCHAR(255)     NOT NULL,
  `file_name`    VARCHAR(255)     NOT NULL,
  `file_content` INT(11)          NOT NULL,
  `file_date`    INT(10)          NOT NULL  DEFAULT '0',
  `file_type`    VARCHAR(64)      NOT NULL  DEFAULT '',
  `file_status`  TINYINT(1)       NOT NULL,
  PRIMARY KEY (`file_id`, `file_modid`),
  UNIQUE KEY `file_id` (`file_id`, `file_modid`)
)
  ENGINE = MyISAM;
